### ISSUE TITLE
Triggers occasional Panics

### ISSUE THREAD

**Issue by carbocation** [andrew/base62.go#1]
Just so this is documented somewhere, this does trigger occasional panics, presumably because the indexing is designed for base64 and not base62. I noted this while using my fork, which hasn't changed any of the underlying code. I don't actually need base62 so I haven't bothered figuring out where the problem lies, but I wanted to document this for others.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
